# Generated by Django 5.1.15 on 2026-05-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='home',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='pages.homepage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featurecard',
            name='home',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.homepage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerlogo',
            name='home',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='pages.homepage'),
            preserve_default=False,
        ),
    ]
