# Generated by Django 5.2.15 on 2026-07-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_hotel_slug_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, help_text='آدرس کامل هتل، توی صفحه\u200cی جزئیات هتل نشان داده می\u200cشود.', max_length=255, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address_en',
            field=models.CharField(blank=True, help_text='آدرس کامل هتل، توی صفحه\u200cی جزئیات هتل نشان داده می\u200cشود.', max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address_fa',
            field=models.CharField(blank=True, help_text='آدرس کامل هتل، توی صفحه\u200cی جزئیات هتل نشان داده می\u200cشود.', max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(blank=True, help_text='مثلاً \u200e+98 21 1234 5678', max_length=50, verbose_name='شماره تماس'),
        ),
    ]
