# Generated by Django 5.2.15 on 2026-07-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_second_hotel_per_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='قیمت تقریبیِ هر شب اقامت به دلار آمریکا — مبنای نمودار قیمت توی صفحه\u200cی جزئیات هتل. چون این سایت درگاه رزرو واقعی ندارد، این یک تخمین شاخص است نه نرخ لحظه\u200cای؛ نسخه\u200cی تومانی نمودار با نرخ روز دلار (که هر روز خودکار به\u200cروز می\u200cشود) از همین عدد محاسبه می\u200cشود.', max_digits=8, null=True, verbose_name='قیمت تقریبی هر شب (دلار)'),
        ),
    ]
