# Generated by Django 5.2.15 on 2026-07-05 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at'], 'verbose_name': 'پست', 'verbose_name_plural': 'پست\u200cها'},
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(verbose_name='متن کامل'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_en',
            field=models.TextField(null=True, verbose_name='متن کامل'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_fa',
            field=models.TextField(null=True, verbose_name='متن کامل'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('sports', 'ورزشی'), ('economy', 'اقتصادی'), ('politics', 'سیاسی'), ('society', 'اجتماعی')], help_text='فقط برای ACDNews. اگر خالی بماند و یکی از این چهار کلمه در تگ\u200cها باشد، خودکار تشخیص داده می\u200cشود.', max_length=20, verbose_name='بخش خبری'),
        ),
        migrations.AlterField(
            model_name='post',
            name='channel',
            field=models.CharField(choices=[('news', 'ACDNews'), ('notes', 'ACDNotes')], default='news', max_length=10, verbose_name='کانال انتشار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, help_text='لینک عکس خارجی (اگر عکسی آپلود نشود، از همین لینک استفاده می\u200cشود)', verbose_name='لینک تصویر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source_name',
            field=models.CharField(blank=True, help_text='فقط برای ACDNews', max_length=120, verbose_name='نام منبع'),
        ),
        migrations.AlterField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, help_text='فقط برای ACDNews', verbose_name='لینک منبع'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True, help_text='اگر خالی بماند، از ابتدای متن ساخته می\u200cشود.', verbose_name='خلاصه'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary_en',
            field=models.TextField(blank=True, help_text='اگر خالی بماند، از ابتدای متن ساخته می\u200cشود.', null=True, verbose_name='خلاصه'),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary_fa',
            field=models.TextField(blank=True, help_text='اگر خالی بماند، از ابتدای متن ساخته می\u200cشود.', null=True, verbose_name='خلاصه'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='با کاما جدا کنید. کلمات ورزشی/اقتصادی/سیاسی/اجتماعی خودکار از این لیست حذف و به دسته تبدیل می\u200cشوند.', max_length=300, verbose_name='تگ\u200cها'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=220, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=220, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_fa',
            field=models.CharField(max_length=220, null=True, verbose_name='عنوان'),
        ),
    ]
