# Generated by Django 5.2.15 on 2026-07-05 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_english_translations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'id'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارش\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'id'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=100, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='category',
            name='page',
            field=models.CharField(choices=[('acdpay', 'ACDPay'), ('acdballoons', 'ACDBallons')], max_length=20, verbose_name='صفحه'),
        ),
        migrations.AlterField(
            model_name='order',
            name='admin_note',
            field=models.TextField(blank=True, help_text='یادداشت داخلی تیم فروش/مالی — مشتری این را نمی\u200cبیند', verbose_name='یادداشت داخلی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.CharField(help_text='شماره واتساپ/تلگرام/بله', max_length=30, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='وقتی مشتری از «محصولات من» حذف می\u200cکند، رکورد پاک نمی\u200cشود؛ فقط مخفی می\u200cشود', verbose_name='مخفی از مشتری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stage',
            field=models.CharField(choices=[('submitted', 'ثبت درخواست'), ('verifying', 'استعلام مدارک'), ('docs_submitted', 'مدارک ارسال شد'), ('payment_info_sent', 'راهنمای پرداخت'), ('payment_submitted', 'پرداخت ثبت شد'), ('payment_confirmed', 'پرداخت تایید شد'), ('card_registered', 'ثبت کارت در بانک'), ('printing', 'در حال چاپ'), ('shipped', 'ارسال شده'), ('availability_confirmed', 'تایید ظرفیت و تاریخ'), ('ticket_issued', 'بلیط صادر شد')], default='submitted', max_length=30, verbose_name='مرحله'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کوتاه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='لینک عکس خارجی (اگر عکسی آپلود نشود، از همین لینک استفاده می\u200cشود)', verbose_name='لینک تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, verbose_name='توضیح کامل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کامل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='long_description_fa',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح کامل'),
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(help_text='به تومان', verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان'),
        ),
    ]
